apiVersion: v1
kind: Service
metadata:
  name: redis-master
  labels:
    app: redis
    role: redis-master
    tier: backend
spec:
  selector:
    app: nodeapp
  ports:
  - port: 6379
    targetPort: 6379
